  package com.java.exception;

public class TryReturn {
public static void main(String[] args) {
	
	
	System.out.println(new A().sum());
}
}

class A{
	
	public int sum(){
		
	
	try{
		
		int a = 10/0;
		
	}catch(Exception e){
		return 10;
	}
	finally{
		System.out.println(" I am in finally block");
	}
	return 20;
	}
}